name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r myproject/requirements.txt
        
    - name: Install pytest
      run: pip install pytest
      
    - name: Install python-dotenv
      run: pip install python-dotenv 
      
    - name: Configure environment variables
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_PASS: ${{ secrets.DATABASE_PASSWORD }}
        
    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ env.SECRET_KEY }}" > .env
        echo "DATABASE_NAME=${{ env.DATABASE_NAME }}" >> .env
        echo "DATABASE_USER=${{ env.DATABASE_USER }}" >> .env
        echo "DATABASE_HOST=${{ env.DATABASE_HOST }}" >> .env
        echo "DATABASE_PORT=${{ env.DATABASE_PORT }}" >> .env
        echo "DATABASE_PASS=${{ env.DATABASE_PASS }}" >> .env

        
    - name: Run tests with pytest
      run: pytest
