name: Django Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r myproject/requirements.txt
    - name: Install pytest
      run: |
        pip install pytest
    - name: Configuring Secrets
      run: echo "DJANGO_SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
    - name: Run tests with pytest
      run: pytest
    - name: Coverage report
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report
